language: go

go:
  - 1.11.x
  - 1.12.x
  - tip

os:
  - linux

branches:
  only:
  - master
  - develop

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

before_install:
  - make deps-test
  - go get -v github.com/mattn/goveralls
  - npm install -g codeclimate-test-reporter

script:
  - go test -covermode count -coverprofile cover.out
  - goveralls -service travis-ci -repotoken $COVERALLS_TOKEN -coverprofile cover.out || true
  - codeclimate-test-reporter < cover.out
