name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]

jobs:
  Go:
    name: Go
    runs-on: ubuntu-latest

    env:
      SRC_DIR: src/github.com/${{ github.repository }}
      GO111MODULE: auto

    strategy:
      matrix:
        go: [ '1.16.x', '1.17.x' ]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Setup PATH
        run: |
          echo "GOPATH=${{ github.workspace }}" >> "$GITHUB_ENV"
          echo "GOBIN=${{ github.workspace }}/bin" >> "$GITHUB_ENV"
          echo "${{ github.workspace }}/bin" >> "$GITHUB_PATH"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ${{env.SRC_DIR}}

      - name: Download dependencies
        working-directory: ${{env.SRC_DIR}}
        run: make deps-test

      - name: Run tests
        working-directory: ${{env.SRC_DIR}}
        run: go test -covermode=count -coverprofile=cover.out

      - name: Send coverage
        uses: essentialkaos/coverage-action@master
        with:
          coverage: ./cover.out
          coveralls: yes
          codebeat: yes

  Aligo:
    name: Aligo
    runs-on: ubuntu-latest

    needs: Go

    env:
      SRC_DIR: src/github.com/${{ github.repository }}
      GO111MODULE: auto

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.x'
        id: go

      - name: Setup PATH
        run: |
          echo "GOPATH=${{ github.workspace }}" >> "$GITHUB_ENV"
          echo "GOBIN=${{ github.workspace }}/bin" >> "$GITHUB_ENV"
          echo "${{ github.workspace }}/bin" >> "$GITHUB_PATH"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ${{env.SRC_DIR}}

      - name: Download dependencies
        working-directory: ${{env.SRC_DIR}}
        run: make deps

      - name: Check Golang sources with Aligo
        uses: essentialkaos/aligo-action@v1
        with:
          path: ${{env.SRC_DIR}}
          files: .
